export { default as Page1 } from './page1';
export { default as Page2 } from './page2';
export { default as pgHome } from './pgHome';
export { default as pgWelcome } from './pgWelcome';
export { default as pgSignIn } from './pgSignIn';
export { default as pgNumber } from './pgNumber';
export { default as pgVerification } from './pgVerification';
export { default as pgLogin } from './pgLogin';
export { default as pgSignUp } from './pgSignUp';
